# # Old Colors
# set -g status-bg "#5D5D5D"
# set -g status-fg "#FFE377"

# # highlight active window
# setw -g window-status-current-bg "#5D5D5D"
# setw -g window-status-current-fg "#FFE377"

# # highlight activity in status bar
# setw -g window-status-activity-fg "#8abeb7"
# setw -g window-status-activity-bg "#1d1f21"

# # pane border and colors
# set -g pane-active-border-bg default
# set -g pane-active-border-fg "#373b41"
# set -g pane-border-bg default
# set -g pane-border-fg "#373b41"

# set -g clock-mode-colour "#81a2be"
# set -g clock-mode-style 24

# set -g message-bg "#8abeb7"
# set -g message-fg "#000000"

# set -g message-command-bg "#8abeb7"
# set -g message-command-fg "#000000"

# set -g mode-bg "#8abeb7"
# set -g mode-fg "#000000"

################
#### Custom ####
################

set -g default-terminal "screen-256color"
# set -g default-terminal "xterm-color"
source-file ~/dotfiles/remote/tmux/tomorrow-night-eighties.tmux

# Maintain sensible window ordering
set-option -g renumber-windows on

# sane scrolling
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Powerline -- no good colorscheme yet  ...
# source "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/powerline/bindings/tmux/powerline.conf"

###################
#### From Book ####
###################

# new mapping for prefix
#unbind C-b
#set -g prefix C-a
set -g prefix `
bind-key ` send-prefix

# Better indexes
set -g base-index 1
set -g pane-base-index 1

# Reload .tmux.conf using Prefix-r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Splitting panes
bind | split-window -h
bind - split-window -v

# empty default window name
bind-key c new-window -n ''

# Moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quick pane selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Mouse support
setw -g mode-mouse on
set -g mouse-select-pane on
set -g mouse-resize-pane on
set -g mouse-select-window on

# Center the window list
set -g status-justify centre

# Smart pane switching with awareness of vim splits
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
