#########################
# Antigen Configuration #
#########################

source ~/dotfiles/zsh/antigen.zsh

# Load oh-my-zsh's library
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh)
antigen bundle git

# Bundles from elsewhere
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle superquest/zsh-thought-provoking-cowsay

# Load theme
antigen theme dst

# Pull the trigger
antigen apply

#############################
# Non-Antigen Configuration #
#############################

alias alacritty='~/bin/alacritty/target/release/alacritty'
alias ctags="`brew --prefix`/bin/ctags"

# FIXME: tmux-yank copies RPROMPT we must kill it for now
export RPROMPT=''

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
